# Generated by Django 4.2.30 on 2026-08-28 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('description', models.TextField(blank=True)),
                ('fulfilment', models.CharField(choices=[('instant', 'Instant — dark store, 18 minutes'), ('scheduled', 'Scheduled — stocked, delivered on a chosen date'), ('bookable', "Bookable — consumes a professional's time slot"), ('made_to_order', 'Made to order — cut or built after ordering')], default='scheduled', max_length=20)),
                ('pricing_unit', models.CharField(choices=[('per_piece', 'Per piece'), ('per_sqft', 'Per sq.ft.'), ('per_running_ft', 'Per running ft.'), ('per_visit', 'Per visit'), ('per_bag', 'Per bag'), ('per_litre', 'Per litre'), ('per_kg', 'Per kg')], default='per_piece', max_length=20)),
                ('gst_rate', models.PositiveSmallIntegerField(choices=[(0, '0%'), (5, '5%'), (12, '12%'), (18, '18%'), (28, '28%')], default=18)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('source_name', models.CharField(blank=True, max_length=60)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('source_image_url', models.URLField(blank=True, max_length=500)),
                ('source_availability', models.CharField(blank=True, max_length=20)),
                ('source_price_paise', models.PositiveIntegerField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(default='Standard', max_length=140)),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('mrp_paise', models.PositiveIntegerField(help_text='List price before discount, in paise')),
                ('price_paise', models.PositiveIntegerField(help_text='Sell price for a standard customer')),
                ('pro_price_paise', models.PositiveIntegerField(blank=True, help_text='Quoin Pro trade rate; blank means Pro pays the same', null=True)),
                ('min_qty', models.PositiveIntegerField(default=1)),
                ('step_qty', models.PositiveIntegerField(default=1)),
                ('is_default', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'ordering': ['price_paise'],
            },
        ),
        migrations.CreateModel(
            name='PriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_qty', models.PositiveIntegerField()),
                ('max_qty', models.PositiveIntegerField(blank=True, help_text='Blank means no upper bound', null=True)),
                ('price_paise', models.PositiveIntegerField()),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['min_qty'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='catalog_pro_categor_891fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='catalog_pro_brand_i_69e6f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='pricetier',
            constraint=models.UniqueConstraint(fields=('variant', 'min_qty'), name='uniq_tier_per_variant_min'),
        ),
    ]
