/**
 * Load the catalogue from the combined competitor export.
 *
 * Ported from the Django `catalog.management.commands.import_catalogue`
 * command, which read the source .docx directly. The repo now carries the
 * extracted CSV (`research/data/all-products.csv`), so this reads that
 * instead — one fewer format to parse, and the file under import is the
 * one under version control.
 *
 * Idempotent: rows are matched on SKU and updated in place, so running it
 * twice does not duplicate the catalogue. Slugs are assigned on creation
 * only — re-importing must never change a URL that has been indexed.
 *
 *   npx tsx prisma/import-catalogue.ts --dry-run
 *   npx tsx prisma/import-catalogue.ts research/data/all-products.csv
 */
/* Must be first: populates process.env before Prisma is constructed. */
import "../src/lib/load-env-file";

import { readFileSync } from "node:fs";
import path from "node:path";

import { Fulfilment, PricingUnit, PrismaClient } from "@prisma/client";

const db = new PrismaClient();

const DEFAULT_CSV = path.join("research", "data", "all-products.csv");
const UNCATEGORISED = "Uncategorised";

/**
 * GST slabs by category. Cement and sanitaryware sit at 28%, most other
 * building materials at 18%. Wrong tax is an invoicing problem, so these
 * are explicit rather than defaulted silently.
 */
const GST_BY_CATEGORY: Record<string, number> = {
  "cement & steel": 28,
  "bathware & plumbing": 18,
  "electricals & lighting": 18,
  "tiling & adhesives": 18,
  "paints & finishes": 18,
  "plywood & laminates": 18,
  "hardware & locks": 18,
  waterproofing: 18,
};

const DEFAULT_GST_PCT = 18;

/**
 * Categories assigned to rows the export left blank.
 *
 * Every uncategorised row came from a source that publishes no category,
 * which was 548 products — more than half the catalogue, unbrowsable. The
 * map is keyed by the product-URL slug and generated by
 * `research/classify-uncategorised.py`, which prefers the merchant's own
 * collection membership over guessing from the name.
 *
 * It is data, not code, on purpose: merchandising corrects a bad call by
 * editing one line of JSON and re-importing, with no deploy.
 */
const CATEGORY_MAP: Record<string, string> = JSON.parse(
  readFileSync(path.join("research", "data", "category-map.json"), "utf8"),
);

/** The product-URL slug is the join key between the export and the map. */
function productSlugOf(url: string): string {
  return url.replace(/.*\/products\//, "").replace(/\/+$/, "");
}

/**
 * GST follows the resolved category, so a row rescued from
 * "Uncategorised" is taxed as what it actually is rather than defaulting.
 */
const GST_BY_RESOLVED: Record<string, number> = {
  "cement & steel": 28,
  "home appliances & security": 18,
  "kitchen & wardrobe fittings": 18,
  "kitchen sinks & faucets": 18,
  "tools & safety": 18,
  "gypsum & false ceiling": 18,
  services: 18,
};

/**
 * Pricing unit inferred from the product name. Order matters — the first
 * match wins, so the more specific patterns come first.
 */
const UNIT_PATTERNS: [RegExp, PricingUnit][] = [
  [/\b(\d+\s*)?(kg|kgs)\b/i, PricingUnit.PER_KG],
  [/\b(\d+\s*)?(ltr|litre|liter|l)\b/i, PricingUnit.PER_LITRE],
  [/\bbag\b/i, PricingUnit.PER_BAG],
  [/\bsq\.?\s?ft|square\s?feet\b/i, PricingUnit.PER_SQFT],
  [/\b(running\s?ft|r\.?ft|per\s?metre|meter|metres)\b/i, PricingUnit.PER_RUNNING_FT],
  [/\b(visit|consultation|inspection|service)\b/i, PricingUnit.PER_VISIT],
];

function guessUnit(name: string): PricingUnit {
  for (const [pattern, unit] of UNIT_PATTERNS) {
    if (pattern.test(name)) return unit;
  }
  return PricingUnit.PER_PIECE;
}

/**
 * Conservative by design. Nothing is marked `INSTANT` on import: that
 * claims a dark store holds the item, which is an inventory fact this
 * export does not carry. Merchandising promotes products to instant once
 * stock is real.
 */
function guessFulfilment(unit: PricingUnit): Fulfilment {
  if (unit === PricingUnit.PER_VISIT) return Fulfilment.BOOKABLE;
  if (unit === PricingUnit.PER_SQFT) return Fulfilment.MADE_TO_ORDER;
  return Fulfilment.SCHEDULED;
}

/** '8,039.0' -> 803900. Integer paise; never float rupees. */
function toPaise(raw: string): number | null {
  const digits = (raw ?? "").replace(/[^\d.]/g, "");
  if (!digits) return null;
  const value = Number.parseFloat(digits);
  return Number.isFinite(value) ? Math.round(value * 100) : null;
}

function slugify(value: string): string {
  return (
    value
      .toLowerCase()
      .normalize("NFKD")
      .replace(/[̀-ͯ]/g, "")
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "") || "item"
  );
}

/**
 * A slug free of collisions. Distinct names routinely collapse onto one
 * slug — "Dr Fixit" and "Dr. Fixit" are different brands that both
 * slugify to "dr-fixit" — so a numeric suffix is appended until free.
 */
function uniqueSlug(base: string, maxLength: number, taken: Set<string>): string {
  const root = slugify(base).slice(0, maxLength);
  let candidate = root;
  let n = 1;
  while (taken.has(candidate)) {
    n += 1;
    const suffix = `-${n}`;
    candidate = `${root.slice(0, maxLength - suffix.length)}${suffix}`;
  }
  taken.add(candidate);
  return candidate;
}

/**
 * Minimal RFC 4180 reader: quoted fields may contain commas and doubled
 * quotes. The export carries no newlines inside fields, so rows are read
 * line by line rather than character by character across the whole file.
 */
function parseCsv(text: string): Record<string, string>[] {
  const lines = text.split(/\r?\n/).filter((line) => line.trim() !== "");
  if (lines.length === 0) return [];

  const splitRow = (line: string): string[] => {
    const cells: string[] = [];
    let cell = "";
    let quoted = false;

    for (let i = 0; i < line.length; i++) {
      const char = line[i];
      if (quoted) {
        if (char === '"') {
          if (line[i + 1] === '"') {
            cell += '"';
            i++;
          } else {
            quoted = false;
          }
        } else {
          cell += char;
        }
      } else if (char === '"') {
        quoted = true;
      } else if (char === ",") {
        cells.push(cell);
        cell = "";
      } else {
        cell += char;
      }
    }
    cells.push(cell);
    return cells;
  };

  const header = splitRow(lines[0]).map((h) => h.trim());
  return lines.slice(1).map((line) => {
    const cells = splitRow(line);
    return Object.fromEntries(header.map((key, i) => [key, (cells[i] ?? "").trim()]));
  });
}

async function main() {
  const args = process.argv.slice(2);
  const dryRun = args.includes("--dry-run");
  const file = args.find((a) => !a.startsWith("--")) ?? DEFAULT_CSV;

  const rows = parseCsv(readFileSync(file, "utf8"));

  let created = 0;
  let updated = 0;
  let skipped = 0;
  let noCategory = 0;
  let reclassified = 0;
  let noPrice = 0;

  /* Slug uniqueness is decided against what is already stored plus what
     this run has assigned, so a single pass cannot collide with itself. */
  const productSlugs = new Set(
    dryRun ? [] : (await db.product.findMany({ select: { slug: true } })).map((p) => p.slug),
  );
  const brandSlugs = new Set(
    dryRun ? [] : (await db.brand.findMany({ select: { slug: true } })).map((b) => b.slug),
  );
  const categorySlugs = new Set(
    dryRun ? [] : (await db.category.findMany({ select: { slug: true } })).map((c) => c.slug),
  );

  const brands = new Map<string, string>();
  const categories = new Map<string, string>();

  async function getBrandId(name: string): Promise<string | null> {
    const trimmed = name.trim();
    if (!trimmed) return null;
    const cached = brands.get(trimmed);
    if (cached) return cached;

    const existing = await db.brand.findUnique({ where: { name: trimmed } });
    const brand =
      existing ??
      (await db.brand.create({
        data: { name: trimmed, slug: uniqueSlug(trimmed, 140, brandSlugs) },
      }));
    brands.set(trimmed, brand.id);
    return brand.id;
  }

  async function getCategoryId(name: string): Promise<string> {
    const trimmed = name.trim() || UNCATEGORISED;
    const cached = categories.get(trimmed);
    if (cached) return cached;

    const existing = await db.category.findFirst({ where: { name: trimmed } });
    const category =
      existing ??
      (await db.category.create({
        data: { name: trimmed, slug: uniqueSlug(trimmed, 160, categorySlugs) },
      }));
    categories.set(trimmed, category.id);
    return category.id;
  }

  for (const row of rows) {
    const sku = row.sku ?? "";
    const name = row.name ?? "";
    if (!sku || !name) {
      skipped++;
      continue;
    }

    const price = toPaise(row.price_inr ?? "");
    if (price === null) {
      noPrice++;
      skipped++;
      continue;
    }

    /* Fall back to the classifier only where the export itself is
       silent; a category the source states always wins. */
    let rawCategory = row.category ?? "";
    if (!rawCategory) {
      const mapped = CATEGORY_MAP[productSlugOf(row.url ?? "")];
      if (mapped) {
        rawCategory = mapped;
        reclassified++;
      } else {
        noCategory++;
      }
    }

    const unit = guessUnit(name);
    const key = rawCategory.toLowerCase();
    const gstRatePct =
      GST_BY_CATEGORY[key] ?? GST_BY_RESOLVED[key] ?? DEFAULT_GST_PCT;

    if (dryRun) {
      created++;
      if (!brands.has(row.brand ?? "") && (row.brand ?? "").trim()) {
        brands.set(row.brand.trim(), "dry-run");
      }
      categories.set(rawCategory.trim() || UNCATEGORISED, "dry-run");
      continue;
    }

    const brandId = await getBrandId(row.brand ?? "");
    const categoryId = await getCategoryId(rawCategory);

    const existing = await db.product.findUnique({ where: { sku } });

    const shared = {
      name,
      brandId,
      categoryId,
      pricingUnit: unit,
      fulfilment: guessFulfilment(unit),
      gstRatePct,
      /* Quoin's own image stays empty; the storefront draws a swatch
         rather than borrowing someone else's photograph. */
      image: "",
      sourceName: row.source || null,
      sourceUrl: row.url || null,
      sourceImageUrl: row.image || null,
      sourceAvailability: row.availability || null,
      sourcePricePaise: price,
    };

    const product = existing
      ? await db.product.update({ where: { sku }, data: shared })
      : await db.product.create({
          data: {
            ...shared,
            sku,
            slug: uniqueSlug(`${row.brand ?? ""} ${name} ${sku}`, 280, productSlugs),
          },
        });

    /* One default variant per product: the export carries a single price
       per row. Real variants are added by merchandising. */
    const variantSku = `${sku}-STD`;
    const variant = await db.productVariant.upsert({
      where: { sku: variantSku },
      update: { mrpPaise: price, pricePaise: price },
      create: {
        sku: variantSku,
        productId: product.id,
        label: "Standard",
        mrpPaise: price,
        pricePaise: price,
        minQty: 1,
        stepQty: 1,
        isDefault: true,
      },
    });

    const tiers = Number.parseInt(row.volume_tiers ?? "0", 10);
    if (Number.isFinite(tiers) && tiers > 0) {
      await db.priceTier.upsert({
        where: { variantId_minQty: { variantId: variant.id, minQty: 1 } },
        update: {},
        create: { variantId: variant.id, minQty: 1, pricePaise: price },
      });
    }

    if (existing) updated++;
    else created++;
  }

  console.info(`created ${created}, updated ${updated}, skipped ${skipped}`);
  console.info(`  brands: ${brands.size}   categories: ${categories.size}`);
  if (reclassified) {
    console.log(`  ${reclassified} rows classified from research/data/category-map.json`);
  }
  if (noCategory) {
    console.warn(`  ${noCategory} rows had no category and were filed under '${UNCATEGORISED}'`);
  }
  if (noPrice) console.warn(`  ${noPrice} rows had an unreadable price`);
  if (dryRun) console.warn("dry run — nothing written");
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(() => db.$disconnect());
